### ISSUE TITLE
Case splitting instantiates meta

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2621]
The function `detAll2` was created by case-splitting.
```agda
open import Agda.Builtin.Nat renaming (Nat to ℕ)
open import Agda.Builtin.Equality

data Vec (A : Set) : ℕ → Set where
  []   :  Vec A zero
  _∷_  :  ∀{n} (x : A) (xs : Vec A n) → Vec A (suc n)

data All₂ {A : Set} {B : Set} (R : A → B → Set) : ∀ {k} → Vec A k → Vec B k → Set where
  []   :  All₂ R [] []
  _∷_  :  ∀ {k x y} {xs : Vec A k} {ys : Vec B k}
          (r : R x y) (rs : All₂ R xs ys) → All₂ R (x ∷ xs) (y ∷ ys)

Det : ∀ {A : Set} {B : Set} (R : A → B → Set) → Set
Det R = ∀{a b c} → R a b → R a c → b ≡ c

detAll₂ : ∀ {A : Set} {B : Set} (R : A → B → Set) (h : Det R) → Det (All₂ R)
detAll₂ R h [] [] = refl
```
I think Agda should report an error here rather than silently setting the meta in the type signature to zero.
@jespercockx opinion?

**Comment by jespercockx** [comment]
I think you're right, when doing an interactive case split it doesn't make sense to instantiate metas, not even in the restricted way we have now.

**Comment by andreasabel** [comment]
Thanks! 
The remaining question is whether we want to accept the above file at all (even if there was no interactive splitting).  Can you please remind me of the issue where we discussed the instantiation of metas in the unifier?  I cannot find it anymore.

**Comment by jespercockx** [comment]
See https://github.com/agda/agda/issues/2074

I only notice now that my fix to that issue doesn't actually fix the example I gave (and I didn't add a test case, shame on me!) Maybe it's better to remove the solution of metavariables during case splitting entirely, there have been enough problems with it. This may break people's code, but I imagine most code (ab)using this feature would already be broken by the fix to #2074. What do you think?

**Comment by jespercockx** [comment]
I just tried to remove the solving of metas from the unifier completely, but this causes the following test cases to fail:
- https://github.com/agda/agda/blob/master/test/Succeed/IndexInference.agda
- https://github.com/agda/agda/blob/master/test/Succeed/Issue707-data.agda (#707)
- https://github.com/agda/agda/blob/master/test/Succeed/Issue1863.agda (#1863)
- https://github.com/agda/agda/blob/master/test/Succeed/Issue1922.agda (#1922)
- https://github.com/agda/agda/blob/master/test/Succeed/Issue2344.agda (#2344)

I don't have a particular problem with moving these to test/Fail.

**Comment by jespercockx** [comment]
To make the examples in IndexInference.agda typecheck, a more restricted version of the algorithm we have now would suffice. In particular, if a function is defined by a single clause **and** it matches on a constructor of an indexed datatype with >1 constructor **and** the constructors of that indexed datatype target conflicting indices (such as `zero` and `suc n` in the case of `Vec`) **and** the index of the variable being matched on is a meta **then** the meta may be instantiated with the constructor applied to fresh metas. I'm not sure if this is worth implementing though just so people can be lazy and put an `_` in their type signature.

**Comment by andreasabel** [comment]
I checked the ones that I think are fine to break:
- [x] https://github.com/agda/agda/blob/master/test/Succeed/IndexInference.agda
  Ok to break.
- [x] https://github.com/agda/agda/blob/master/test/Succeed/Issue707-data.agda (#707)
  Ok to break, weird spooky action at a distance we need not support.
- [x] https://github.com/agda/agda/blob/master/test/Succeed/Issue1863.agda (#1863)
  Ok to break, type signature is incomprehensible with such holes.
- [ ] https://github.com/agda/agda/blob/master/test/Succeed/Issue1922.agda (#1922)
  I think this one should not be broken.  Maybe for extended-lambdas, we need something special.
- [x] https://github.com/agda/agda/blob/master/test/Succeed/Issue2344.agda (#2344)
  Why does this break?

**Comment by andreasabel** [comment]
This issue should be discussed in a wider group @nad @UlfNorell

**Comment by jespercockx** [comment]
For #1922 I agree that it should not be broken, but this seems to be an issue with how extended lambdas are checked rather than with the pattern matching unifier. If you put a hole in place of the extended lambda, Agda infers correctly that it should have type `Fin one -> Bool` (no metas). However, this information is apparently not used for checking the extended lambda. Is there a particular reason why not?

The test case for #2344 breaks because the type of `i` is `Fin (_m_23 A X)`. If you case split on `i`, the meta `_m_23` has to be instantiated to `suc _` in order for the unification to succeed. So it's quite similar to the first three broken cases I think.

**Comment by andreasabel** [comment]
Ok, then it is only the extended lambdas.  

The type information is propagated into the extended lambda too late, I guess. Consider:
```agda
open import Agda.Builtin.Nat

postulate
  f : {A : Set} → (A → A) → A

test : Set
test = f λ{ zero → {!!} }
```
This produces the errors:
```
Nat !=< Set of type Set
when checking that the expression f (λ { zero → ? }) has type Set

Incomplete pattern matching for .extendedlambda0. Missing cases:
  .extendedlambda0 (suc x)
when checking the definition of .extendedlambda0
```
You see that Agda first checks the extended lambda of type `_1 -> _1`, instantiating `_1 := Nat` and noticing that there is no case for successor.  Then, once it has reached the end of the application `f {_1} \{...}` it discovers that `_1` should be actually `Set`.  
Postponing checking of LHSs would fix this. See #480.

**Comment by andreasabel** [comment]
I realized I already reported this issue in 2015, see #1611.  The example there is:
```agda
data D : Bool → Set where
  dt : D true
  df : D false

Fails : ∀{b : Bool} → D _ → Set
Fails dt = Bool
Fails df = Bool
```
with error
```
The case for the constructor df is impossible
because unification ended with a conflicting equation
  false ≟ true
Possible solution: remove the clause, or use an absurd pattern ().
when checking that the pattern df has type D true
```

**Comment by andreasabel** [comment]
Ok to merge, I guess.  
We should fix #1922 in a different way then.
Looking at https://github.com/agda/agda/commit/b6b3f7a257e8fe03396ec1cd5a73878941c1bf56 maybe we just have to catch more errors addtitionally to IllTypedPattern, say also this "Cannot decide...".

**Comment by jespercockx** [comment]
Ok, I'm trying out a first crude fix to #1922 in the same spirit now. Ideally we'd keep track of which metas are blocking a unification problem, but I can use an over-approximation of the set of metas for now.

**Comment by asr** [comment]
I will include the fix in the RC, so I changed the milestone to 2.5.3.

**Comment by andreasabel** [comment]
@jespercockx Please document the change in the CHANGELOG.
