### ISSUE TITLE
Agda 2.5.3 release

### ISSUE THREAD

**Issue by ilovezfs** [agda/agda#2659]
Because the `agda` formula in Homebrew has a runtime dependency on GHC, not just build-time, it is especially important for us to be able to build `agda` with the latest GHC. Otherwise, we cannot upgrade `cabal-install`, and the 2.0 release for `cabal-install` is due out imminently, as Cabal 2.0 has already been tagged.

The `stable-2.5` branch seems to build fine with GHC 8.2.1. Are there any remaining blockers to getting a 2.5.3 tagged? That would be much appreciated downstream!

**Comment by andreasabel** [comment]
I had a look at the current list of regressions.  None of these is not already released, thus, shipping 2.5.3 should not make things worse than they already are (to take a very pessimistic stance ;)).

Only my recent refactorings for #1293 worry me a bit, we may need a bit time to weed out possible new regressions there.

**Comment by ilovezfs** [comment]
@andreasabel thanks! Please let me know if there's anything you'd like tested through our CI.

**Comment by andreasabel** [comment]
I will go on vacation now and cannot continue to work for a release.
@UlfNorell can you release in August? Or @asr?

Just for the release. the following diff in `Agda.Syntax.Abstract.Name` (connected to #1293) should be reverted, to make sure that the internal change of Name printing does not have some weird unexpected effects.
```diff
--- deriving instance Show Name
--- deriving instance Show ModuleName
--- deriving instance Show QName
+deriving instance Show Name
+deriving instance Show ModuleName
+deriving instance Show QName
 deriving instance Show a => Show (QNamed a)
 deriving instance Show AmbiguousQName
 
--- | Only use this @show@ function in debugging!  To convert an
---   abstract 'Name' into a string use @prettyShow@.
-instance Show Name where
-  -- Andreas, 2014-10-02: Reverted to nice printing.
-  -- Reason: I do not have time just now to properly fix the
-  -- use of Show Name for pretty printing everywhere.
-  -- But I want to push the fix for Issue 836 now.
-  show = prettyShow
-
--- | Only use this @show@ function in debugging!  To convert an
---   abstract 'ModuleName' into a string use @prettyShow@.
-instance Show ModuleName where
-  show = prettyShow
-
--- | Only use this @show@ function in debugging!  To convert an
---   abstract 'QName' into a string use @prettyShow@.
-instance Show QName where
-  show = prettyShow
```

**Comment by UlfNorell** [comment]
I'll be back from vacation the week of the 7th, so I can continue work on the release then.

**Comment by asr** [comment]
Under the assumption that we'll release Agda 2.5.4, I created the 2.5.5 milestone.

**Comment by andreasabel** [comment]
@asr: I thought we release 2.5.3 first.  (But nothing against a 2.5.5 milestone.)
@UlfNorell: good!

I dedicate this issue to the discussion of the 2.5.3 release.

**Comment by asr** [comment]
> @asr: I thought we release 2.5.3 first.

I just was thinking in retaking the initial tradition and release even version numbers, i.e. 2.5.4, 2.5.6 and so on, but it's OK if we release using the 2.5.3 version number.

**Comment by andreasabel** [comment]
If I remember correctly, this is the next release of the stable branch (2.5.1, 2.5.2, 2.5.3).
The current master, once it becomes stable, will be released as (2.6.1).
I forgot the exact logic behind this, but I think it is because early adopters work already with 2.6.0, and when we officially release it, it should have a strictly higher version number.
The discussion is here: #1941.
It seems not fully up-to-date with our practice, though.
We should put the versioning policy in some file, maybe in https://github.com/agda/agda/blob/master/notes/agda-releases.txt .

**Comment by gallais** [comment]
Should the regression in #2667 count as a release blocker?

**Comment by ilovezfs** [comment]
Any updates here?

**Comment by ilovezfs** [comment]
Just a heads up that cabal-install 2.0.0.0 is now on Hackage.

**Comment by ilovezfs** [comment]
Given that it is unclear to me what the time table here is, I have proceeded without a new Agda release so as not to hold up the cabal-install 2.0.0.0 upgrade in Homebrew.

To do this, I have shipped a "fake" Agda version "2.5.3-alpha1" as the _stable_ spec in Homebrew:
https://github.com/Homebrew/homebrew-core/commit/e1f505f26e25501c0561de80ffd48dff88b0b353

2.5.3-alpha1 is defined as
https://github.com/agda/agda/commit/e3f598313ceac6de8903f9e5693efb30435691fc
https://github.com/agda/agda-stdlib/commit/c47a1516aaf40892f97b14e3fd1f2bd0c628cadc

**Comment by UlfNorell** [comment]
I'm back from holidays (as mentioned above) and have started working on the release. Barring major blockers I'm expecting to get it out by early next week.

**Comment by UlfNorell** [comment]
> Should the regression in #2667 count as a release blocker?

I don't think so. While it is a regression, it's a regression of the error message (if I'm reading your analysis correctly).

My plan for `2.5.3` is to release without worrying too much about existing bugs. Hopefully there will be time for a bug fixing spree and a `2.5.3.1` release in the not too distant future.

**Comment by ilovezfs** [comment]
>My plan for 2.5.3 is to release without worrying too much about existing bugs.

That would be great. I don't like inventing versions :(

**Comment by asr** [comment]
@UlfNorell, I see there are only two issues labelled with the 2.5.3 milestone. Good! 

Make me a signal when the stable-2.5 branch is ready and I will start preparing the release.

**Comment by UlfNorell** [comment]
Will do, thank you @asr.

**Comment by UlfNorell** [comment]
@asr: I think `stable-2.5` is ready now. Some Travis jobs are still running, but I expect no problems from those.

**Comment by favonia** [comment]
@UlfNorell Since several hours ago I have been seeing the build with the environment `TEST=MAIN GHC_VER=7.8.4 BUILD=CABAL CABAL_VER=1.18` keeps failing due to some dependency issue. Is this expected?

**Comment by UlfNorell** [comment]
I filed #2680 for that. I didn't investigate in detail, but it seems like `text-icu` fails to install with `ghc-7.8`. Since that dependency is not enable by default, and it doesn't seem like it's our fault, I'm not too worried about it.

**Comment by asr** [comment]
As preparation for the release, I have "frozen" the stable-2.5 branch by creating the release-2.5.3 branch. You can continue pushing on stable-2.5/master as usual.

**Comment by andreasabel** [comment]
I pushed fixes for #2684 and #2686 onto stable-2.5, but these are not urgent for release.
After the release, https://github.com/agda/agda/commit/cba35819399876a489be0e79b4bcc4ab95054df1 should be reverted.

**Comment by asr** [comment]
I will include these fixes in the RC.

**Comment by asr** [comment]
I have tested the installation of  [2.5.3 RC 1](http://www1.eafit.edu.co/asr/tmp-asr/Agda-2.5.2.20170813.tar.gz) on Ubuntu.

Could someone test the installation on Windows and Mac OS using the following instructions:

```
  $ tar xzf Agda-2.5.2.20170813.tar.gz
  $ cd Agda-2.5.2.20170813
  $ cabal install
```

Which GHC version(s) did you use?

**Comment by andreasabel** [comment]
I tried, with some effort, to use the github API bindings for Haskell to get the list of closed issues for this release.  I added them to CHANGELOG (but deleted the ones that only affect our development process, like testsuite etc.).
See `src/issues/` for the code I wrote.  Can be developed further, e.g., at the next release.

**Comment by asr** [comment]
@andreasabel, Great! Good job!

**Comment by andreasabel** [comment]
Thanks.  It would have been a more pleasant coding session if the `github` package was better documented and had less design glitches. 

From my side, there is nothing very urgent to do for the release left, I have no more bug fixes planned.
I think we can go ahead.

**Comment by UlfNorell** [comment]
RC 1 works fine on MacOS, ghc-8.2.1. Stay tuned for Windows results...

**Comment by UlfNorell** [comment]
Window 10, ghc-8.0.1 works ok.

**Comment by asr** [comment]
Please note that the RC announced on the mailing lists corresponds to the stable branch on commit 7750254e93c722b2cc642f8b4240a212cc6de4b2.

**Comment by nad** [comment]
```
$ cabal outdated
Outdated dependencies:
binary >=0.7.2.1 && <0.9 (latest: 0.9.0.0)
```

**Comment by asr** [comment]
`binary 0.9.0.0` was deprecated in [Hackage](http://hackage.haskell.org/package/binary/preferred).

**Comment by nad** [comment]
From https://www.stackage.org/package/binary:

> 0.8.5.0 was first released as version 0.9.0.0. It didn't have any breaking changes though, so it was again released as version 0.8.5.0 according to PVP. Next breaking release of binary will be version 0.10.0.0.

**Comment by ilovezfs** [comment]
Any news on the 2.5.3 front?

**Comment by nad** [comment]
Some issues are still unresolved:
* [x] #2604, #2725: Mostly fixed on the Issue2604 branch. One known problem remains to be fixed. I wouldn't mind if we delayed the release of this new feature.
* [x] #2727: Documents a regression, as well as another problem. The regression could perhaps be fixed by rolling back commit c46725e6b755cfc1fd42b916d841641d9e4ce892.
* [x] #2728: A regression.

**Comment by Blaisorblade** [comment]
- [x] #2731 is a build failure (on 2.5.2) with latest happy from two days ago — @ilovezfs that also sounds potentially relevant to Homebrew. Since `happy` has no fixed version, does your Agda formula still build from source?

EDIT: #2731 is fixed on release-2.5, which IIUC will be merged in release-2.5.3 and end up in the release.

**Comment by ilovezfs** [comment]
@Blaisorblade thanks for the heads up. Workaround in https://github.com/Homebrew/homebrew-core/pull/17622.

**Comment by asr** [comment]
No more open issues with milestone 2.5.3. Great!

I'll wait for the beautiful green in Travis before freezing the branch.

**Comment by asr** [comment]
I have "frozen" the stable-2.5 branch to make the release of 2.5.3. You can continue pushing on stable-2.5/master as usual.

**Comment by asr** [comment]
Argh! I saw that the [CHANGELOG](https://hackage.haskell.org/package/Agda-2.5.3/changelog) layout is messed up after releasing to Hackage.

**Comment by asr** [comment]
I feel that closing this issue was a great *team* work! Thanks everyone!

**Comment by andreasabel** [comment]
Thanks Andrés, for ensuring a stable release!

> Argh! I saw that the CHANGELOG layout is messed up after releasing to Hackage.

Ulf's beautiful table is not rendered as such:
```
The translation of old pragmas into new ones is as follows:

Old | New --- | --- {-# COMPILED f e #-} | {-# COMPILE GHC f = e #-} {-# COMPILED_TYPE A T #-} | {-# COMPILE GHC A = type T #-} {-# COMPILED_DATA A D C1 .. CN #-} | {-# COMPILE GHC A = data D (C1 | .. | CN) #-} {-# COMPILED_DECLARE_DATA #-} | obsolete, removed {-# COMPILED_EXPORT f g #-} | {-# COMPILE GHC f as g #-} {-# IMPORT M #-} | {-# FOREIGN GHC import qualified M #-} {-# HASKELL code #-} | {-# FOREIGN GHC code #-} {-# COMPILED_UHC f e #-} | {-# COMPILE UHC f = e #-} {-# COMPILED_DATA_UHC A D C1 .. CN #-} | {-# COMPILE UHC A = data D (C1 | .. | CN) #-} {-# IMPORT_UHC M #-} | {-# FOREIGN UHC __IMPORT__ M #-} {-# COMPILED_JS f e #-} | {-# COMPILE JS f = e #-}
```

**Comment by UlfNorell** [comment]
Oh no! My poor table.

Very good job everyone though!

**Comment by ilovezfs** [comment]
2.5.3 shipped in Homebrew (https://github.com/Homebrew/homebrew-core/pull/17853). Thanks everyone! :heart:

**Comment by asr** [comment]
> Ulf's beautiful table is not rendered as such:
> ```
> The translation of old pragmas into new ones is as follows:
>
>Old | New --- | --- {-# COMPILED f e #-} | {-# COMPILE GHC f = e #-} {-# COMPILED_TYPE A T #-} | {-# COMPILE GHC A = type T #-} {-# COMPILED_DATA A D C1 .. CN #-} | {-# COMPILE GHC A = data D (C1 | .. | CN) #-} {-# COMPILED_DECLARE_DATA #-} | obsolete, removed {-# COMPILED_EXPORT f g #-} | {-# COMPILE GHC f as g #-} {-# IMPORT M #-} | {-# FOREIGN GHC import qualified M #-} {-# HASKELL code #-} | {-# FOREIGN GHC code #-} {-# COMPILED_UHC f e #-} | {-# COMPILE UHC f = e #-} {-# COMPILED_DATA_UHC A D C1 .. CN #-} | {-# COMPILE UHC A = data D (C1 | .. | CN) #-} {-# IMPORT_UHC M #-} | {-# FOREIGN UHC __IMPORT__ M #-} {-# COMPILED_JS f e #-} | {-# COMPILE JS f = e #-}
>```

Hackage currently doesn't support tables, see  https://github.com/haskell/hackage-server/issues/565.
