### ISSUE TITLE
Release Agda 2.5.4

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#2875]
I think we should aim to release Agda 2.5.4 before the next Agda's implementor's meeting.  What do you think?

**Comment by MatthewDaggitt** [comment]
Not quite on topic, but I would be happy to do a standard library release around then. There are definitely some useful things now included that should go out.

**Comment by UlfNorell** [comment]
Sounds like a plan.

**Comment by asr** [comment]
When we are ready, I can make the releases (candidate and final).

**Comment by asr** [comment]
I created the 2.5.5 milestone. Please start to relabel the open issues which won't be fixed in 2.5.4.

**Comment by xekoukou** [comment]
I wish issue #2839 makes it in release 2.5.4.

**Comment by andreasabel** [comment]
> I wish issue #2839 makes it in release 2.5.4.

Sorry, but this seems unlikely, there is no PR of fix of this yet.  Once we decided we want to release, we have to concentrate on eliminating regressions.

**Comment by xekoukou** [comment]
No problem. I was expecting as such.

**Comment by MatthewDaggitt** [comment]
I take it the release before AIM didn't make it. Is there a new target date?

**Comment by UlfNorell** [comment]
No open issues with `2.5.4` milestone! Quick, release before we get any new ones!!

**Comment by asr** [comment]
Great! I'll make the release candidate.

**Comment by asr** [comment]
As preparation for the release, I have "frozen" the `stable-2.5` branch by creating the `release-2.5.4` branch. You can continue pushing on `stable-2.5`/`master` as usual.

**Comment by asr** [comment]
I uploaded to Hackage the package candidate [2.5.4 RC 1](https://hackage.haskell.org/package/Agda-2.5.3.20180519/candidate) and I tested its installation on Ubuntu.

Could someone test the installation on macOS and Windows using the following instruction:

```bash
$ cabal install https://hackage.haskell.org/package/Agda-2.5.3.20180519/candidate/Agda-2.5.3.20180519.tar.gz
```

**Comment by UlfNorell** [comment]
- [x] MacOS X 10.13.4, ghc-8.4.2
- [x] Windows 10, ghc-8.4.2

**Comment by UlfNorell** [comment]
@asr: I fixed #3067 with efc802e. I pushed it to `stable-2.5` and merged into `master` as usual, but the fix should be included in the release.

**Comment by asr** [comment]
> but the fix should be included in the release.

Done. I included that commit in the `release-2.5.4` branch.

**Comment by andreasabel** [comment]
It seems like #2976 now also affects 2.5.4 (used to only affect 2.6.0).  We can't release like that.
Note that this bug prevents any use of Agda in emacs 24. `C-c C-l` is answered by
```
agda2-abort-if-in-progress: Another command is currently in progress
(if a command has been aborted you may want to restart Agda)
```

**Comment by UlfNorell** [comment]
Should be included in release: Fix of #3074 (1439d02)

**Comment by UlfNorell** [comment]
Another one: #3004 (765a4fb)

**Comment by UlfNorell** [comment]
Another one. Time to make a list:

- [x] #3074 (1439d02)
- [x] #3004 (765a4fb)
- [x] #3075 (56c380b)

**Comment by asr** [comment]
I renamed the `type: regression` label to `regression`. Please continue using that label *and* the `type: bug` label on regressions. Note that you also can use a `regression-X.Y.Z` label .

**Comment by asr** [comment]
I also renamed the `type: release-blocker` label to `release-blocker`. Please continue using that label *and* a`type: SOMETHING` label on release-blocker issues.

**Comment by UlfNorell** [comment]
- [x] #3079 (cd4ed87)
- [x] #3080 (be86cdf)
- [x] #3072 (b63cf52)
- [x] #351 (2b66955) (already fixed, added test case)

**Comment by UlfNorell** [comment]
- [x] #2902 (61b5a86) (not closed)
- [x] #2902 (3519913) (test case)

**Comment by asr** [comment]
@UlfNorell, also points me out the new test cases.

**Comment by UlfNorell** [comment]
Ok.

**Comment by asr** [comment]
When labelling an issue using  `regression-X.Y.Z` also label it with `regression`, please.

In fact, I propose to remove the `regression-X.Y.Z` labels. Does any one disagree?

**Comment by UlfNorell** [comment]
I think the `regression-X.Y.Z` labels are useful. It makes a difference whether the regression has already been released. Although I don't hold with people tagging issues with `regression in 2.5.4` before we've even released `2.5.4`. I think that's overly pessimistic.

I can see the point of tagging with both `regression` and `regression-X.Y.Z` when applicable though.

**Comment by asr** [comment]
- [x] #695 (76583cf2020f281b1f56246a460cc0142993a139) (already fixed, only test case)

**Comment by nad** [comment]
More commits to include:
- [x] [ test/interaction ] Made RunAgda.command more general. (00be67068d4aab1a3e7361906566b71ad104ae87).
- [x] #3082 (f78816009).
- [x] [ Emacs mode ] Added an Edebug specification for a macro. (3cf67e74fd968585f9f1a6c55e492fc13f294db2).
- [x] #2794 (838df24f9).
- [x] #2306 (30f696f2f).
- [x] #3084 (ea16f5cf830b980751bdbd27165b706812be1335).

Note that, because it is non-trivial to test the Emacs mode, I am not 100% certain that my fixes are correct. It may be a good idea to leave people a little time to test the latest version before we release.

**Comment by asr** [comment]
> It may be a good idea to leave people a little time to test the latest version before we release.

@nad, I was planning to make the release *tomorrow* (module no open bugs). What did you mean for `little time`?

**Comment by asr** [comment]
Also points me out *any* changes to the test-suite.

**Comment by jespercockx** [comment]
- [x] #3085 (1cf40a49398ad0a7b69273bc9e8c635234add996)

**Comment by nad** [comment]
I still haven't managed to type-check all the old code that I maintain using the latest version of Agda (once #3083 has been investigated I'll take another look), and we have pushed lots of changes recently (bug fixes could introduce regressions), so I don't think we should release 2.5.4 tomorrow. I suggest that we wait one week and release just before the next Agda meeting.

**Comment by asr** [comment]
> I suggest that we wait one week and release just before the next Agda meeting.

OK. I'll make the release next week.

**Comment by UlfNorell** [comment]
It might make sense to release RC-2 tomorrow though.

**Comment by UlfNorell** [comment]
- [x]  #3083 (b02c03c)

**Comment by asr** [comment]
> - [X] #3085 (1cf40a49398ad0a7b69273bc9e8c635234add996)

@jespercockx, why you didn't include 421904022f0f349e74c2be0aeb9dfa8e51f6112c in the above list?

**Comment by nad** [comment]
> (once #3083 has been investigated I'll take another look)

I found another problem that I have started investigating...

**Comment by jespercockx** [comment]
> @jespercockx, why you didn't include 4219040 in the above list?

I'm sorry, it should have been included as well. I somehow thought the change was related to my work on adding `Prop` (which will not be in the release) but apparently I was wrong. The output of that test case is very hard to decypher.

**Comment by asr** [comment]
Missing commit:

- [x] [ test ] Update test output for interaction/Issue157b.agda (421904022f0f349e74c2be0aeb9dfa8e51f6112c)

**Comment by asr** [comment]
> I'm sorry, it should have been included as well. I somehow thought the change was related to my work on adding `Prop` (which will not be in the release) but apparently I was wrong.

Well, you wasn't wrong completely. I cherry-picked 4219040 but I had to fix some conflicts because this test output also was modified when adding `Prop` in 9087981.

Note that this is the first time I got a conflict when cherry-picking commits.

**Comment by asr** [comment]
It is great that *many* of you are pushing fixes for the release, but I guess I won't have the enough bandwidth for handling all of them. I think it was a good idea to postpone the release for one week, but I guess there will be several new commits to be included. If you have some new change to be included in the release, I propose the following work-flow:

1. push your change in the `release-2.5.4` branch
2. wait for the green on Travis
3. cherry-pick (**don't merge**) your change in `stable-2.5`
    (when cherry-picking I use the `-x` option)
4. merge `stable-2.5` into `master` as usual

**Comment by asr** [comment]
> It might make sense to release RC-2 tomorrow though.

It's a good idea. I'll release RC 2. Please don't push anything to the `release-2.5.4` branch.

**Comment by asr** [comment]
You can continue pushing to the `release-2.5.4` branch.

**Comment by andreasabel** [comment]
I introduced the `regression in 2.5.4` label to mark regressions in the RC over 2.5.3.  The intention is that no such regression gets actually released.

**Comment by WolframKahl** [comment]
> I introduced the `regression in 2.5.4` label to mark regressions in the RC over 2.5.3.

Perhaps call it ``regression wrt. 2.5.3'' or ``regression over 2.5.3''?

**Comment by andreasabel** [comment]
No, I think the name is fine, it is the same as for the other releases.
If you fix a `regression in X` issue before the final release of `X`, you can remove that tag from the issue.

**Comment by UlfNorell** [comment]
Yes, that's what I've been doing. My comment about the label was not entirely serious...

**Comment by andreasabel** [comment]
Probably needlessly, I'd like to remind of the `closed-issues` script to add the list of closed issues for 2.5.4 to the CHANGELOG once the list has finalized.
https://github.com/agda/agda/blob/master/src/closed-issues/closed-issues-for-milestone.cabal

However, this list will not be accurate because some issues have been closed without fixing and still have the milestone 2.5.4 tag. (I am talking about the issues we have abandoned as not worth/feasible to fix.)

**Comment by asr** [comment]
Yep! This task is in my TODO list.

**Comment by asr** [comment]
Commit to include:
- [x] #1268 (6a3e83e69f1569dc09c9be1e47f30e85cbf4787c) (already fixed, only test case)

**Comment by asr** [comment]
> However, this list will not be accurate because some issues have been closed without fixing and still have the milestone 2.5.4 tag. (I am talking about the issues we have abandoned as not worth/feasible to fix.)

When reading that #1032 was closed by `status: wontfix` I thought in this situation. I see three options:

1. Remove the milestone tag from those issues with status `abandoned`, `duplicated`, `wontfix`,  or `working-as-intended`, or label `dev-op`.

2. Write in the CHANGELOG *closed* issues (meaning fixed or the status pointed in 1.)

3. Keep the milestone tag, write *fixed* issued in the CHANGELOG and manually remove from the list generated by the `closed-issues` script the issues with the status pointed in 1.

Thinking from an user point of view, I prefer the second option.

**Comment by andreasabel** [comment]
I'd tend to either 1. or 3.  As a user, if my issue appeared in the list of closed issues in the release notes, I would assume the problem I reported has been solved.  
(Or, put differently, if we merely decide to not fix a problem, we shouldn't broadcast it as a closed issue.)
I imagine users refer to this list when deciding whether to update their version of Agda. If an important issue that affected them is fixed, that's a reason to upgrade.

**Comment by asr** [comment]
Commit to include:
- [x] #1363 (b5af02bfecf9eac788e615e2c26cc65feb2d80c9) (already fixed, only test case)

**Comment by andreasabel** [comment]
- [x] #3090 746eda4e2705e9648a090fcbf0d4e3d437554854

**Comment by asr** [comment]
Commit to include:
- [x] #1169 (37b2af1ea0cf0b39afc6fc90fbe1a6a2851bb231) (already fixed, only test case)

**Comment by asr** [comment]
Commit to include:
- [x] #1384 (90dff71272772c744d960bc898f1d9c28aa0bead) (already fixed, only test case)

**Comment by asr** [comment]
Commit to include:
- [x] #1425 (8efa6a5d4e2b0fbf3ac3c201bae01c2e4df22f66) (already fixed, only test case) (cherry-picked in 1de4f875bb033e29202cd9ce4091836fab0757bb)

**Comment by asr** [comment]
> I'd tend to either 1. or 3.  As a user, if my issue appeared in the list of closed issues in the release notes, I would assume the problem I reported has been solved.  
(Or, put differently, if we merely decide to not fix a problem, we shouldn't broadcast it as a closed issue.)
I imagine users refer to this list when deciding whether to update their version of Agda. If an important issue that affected them is fixed, that's a reason to upgrade.

OK. I'll follow 3. (I'll see if I can change 'manually remove' by 'automatically remove', though).

**Comment by asr** [comment]
> However, this list will not be accurate because some issues have been closed without fixing and still have the milestone 2.5.4 tag. (I am talking about the issues we have abandoned as not worth/feasible to fix.)

We also to need to remove the "internal" (test-suite, Travis, Makefile, etc.) issues from the list. Any proposals for a label name for these issues? (I don't like "internal").

**Comment by fredrikNordvallForsberg** [comment]
> We also to need to remove the "internal" (test-suite, Travis, Makefile, etc.) issues from the list. Any proposals for a label name for these issues? (I don't like "internal").

How about "infrastructure"?

**Comment by UlfNorell** [comment]
Or `devops` / `dev-ops`?

**Comment by asr** [comment]
Thanks. I'll label those issues with `dev-ops`. Please continue using this label.

**Comment by andreasabel** [comment]
What is the long form of "dev-ops"?

**Comment by UlfNorell** [comment]
https://en.wikipedia.org/wiki/DevOps

**Comment by andreasabel** [comment]
Fancy word for a natural self-suggesting method.  Sounds like "PsyOps" and "CovertOps".

**Comment by andreasabel** [comment]
- [ ] #3095 (after a review)

**Comment by asr** [comment]
Commit to include:
- [x] #3096  (bd678198820f8ab1a63320baabdbc1f65a76c35d) (supported GHC 8.4.3)

**Comment by asr** [comment]
@andreasabel [wrote](https://github.com/agda/agda/issues/3095#issuecomment-393224571):

> I can't promise to make this work until the deadline (June 3)

My plan is to make the final release on June 2.

**Comment by asr** [comment]
Release time... The `release-2.5.4` branch is frozen.

**Comment by asr** [comment]
Commit to include:
- [x] #2875 (1449586222f85128de90913f01a7a0b948fc869c) (Added list of closed issues to the CHANGELOG)

**Comment by nad** [comment]
The changelog contains a long list of closed issues. I assume that quite a few of these issues do not relate to bugs in previous versions of Agda, or to new features introduced in this version, but to bugs in previous development versions that have never been released. I think the list would be more useful if such issues were not included.

**Comment by asr** [comment]
> The changelog contains a long list of closed issues. I assume that quite a few of these issues do not relate to bugs in previous versions of Agda, or to new features introduced in this version, but to bugs in previous development versions that have never been released. I think the list would be more useful if such issues were not included.

I agree but I don't know how to choose those issues from the bug-tracker using the current tags. Any ideas?

**Comment by asr** [comment]
I have uploaded to Hackage Agda [2.5.4](https://hackage.haskell.org/package/Agda-2.5.4).

**Comment by asr** [comment]
Great job everyone, Agda 2.5.4 was released!

And a special acknowledgement to Ulf for his *comprehensive* revision of the old issues!

**Comment by jespercockx** [comment]
Also thanks to @asr for the smooth release!

**Comment by UlfNorell** [comment]
Yes, awesome work everyone!  🎉🎈🍰

**Comment by nad** [comment]
Yes, thanks to all!

> I agree but I don't know how to choose those issues from the bug-tracker using the current tags. Any ideas?

Not with the current tags, this was more of an idea for the future.

**Comment by andreasabel** [comment]
The easiest is to add a new tag "mention-in-changelog" that can be selected by the one who closes the issue.

**Comment by asr** [comment]
> The easiest is to add a new tag "mention-in-changelog" that can be selected by the one who closes the issue.

I agree with add this tag, but @nad is talking about other issues:

> bugs in previous development versions that have never been released

**Comment by UlfNorell** [comment]
Maybe a tag `released-bug`? That makes more sense to apply right a way.

**Comment by asr** [comment]
> Maybe a tag `released-bug`? 

No. The `closed-issues` program lists *all* the closed issues (by milestone) and we are using tags for *excluding* (not including) issues from that list.

So, for excluding the "bugs in previous development versions that have never been released", we should tag them. I suggest the `non-released-bug` tag.
 
Right now, we are excluding issues tagged with  

`status: abandoned`,
`status: duplicated`,
`status: invalid`,
`status:  wontfix`, 
`status: working-as-intended` or
`dev-op`.

**Comment by andreasabel** [comment]
Maybe a tag like `latest` or `development-only`.

**Comment by andreasabel** [comment]
We could actually use the tags `stable` and `master` which identify issues as not on the released versions.

**Comment by asr** [comment]
We have used the tag `stable`/`master` for issues in the `stable-2.5`/`master` branch but not in the `master`/`stable-2.5` branch.

**Comment by andreasabel** [comment]
Actually, I created the `stable` tag today.  But yes, we used the `master` tag for recent issues that only affect the master branch, and we can continue to do so.  The `stable` tag can be used for recent issues that affect stable and may also affect master.  Together, they give us the set of issues that have been fixed before they ever entered a released version.

**Comment by UlfNorell** [comment]
See also #3104 before you commit to any tag names.

**Comment by asr** [comment]
> Actually, I created the `stable` tag today.  But yes, we used the `master` tag for recent issues that only affect the master branch, and we can continue to do so.  The `stable` tag can be used for recent issues that affect stable and may also affect master.  Together, they give us the set of issues that have been fixed before they ever entered a released version.

I think a unique tag (e.g. `non-released-bug`) is less confusing.
