### ISSUE TITLE
Release Agda 2.6.1.2

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#4749]
Is there a chance to release 2.6.1.1 before the imminent Summer?
At least with fixes for these critical issues:
- [ ] #4526 bad performance (nix) 
- [X] #4569 Build failure with dynamic linking
- [ ] #4613 compilation failure (nix)

**Comment by asr** [comment]
Steps: i) fixing the above critical issues and ii) decide if cherry-pick the commits fixing those issues on 2.6.1 is an option.

**Comment by pnlph** [comment]
I have a question, will the version `2.6.1.1` include #4629 ?

The cubical library does not type check with the current version since agda/cubical#341 because of the flag `--no-import-sorts`.

**Comment by UlfNorell** [comment]
It will not include #4629.

**Comment by guillaumebrunerie** [comment]
I think that the cubical library is only supposed to work with the development version of Agda for now.

**Comment by andreasabel** [comment]
For the sake of releasing Agda to stackage (https://github.com/agda/agda/issues/4672#issuecomment-707092300), we have to release at least two commits: 
- [x] 292f7d8c3def7e69ce9e79c67c895d6a4956dc5f upgrade to latest `aeson`
- [x] 0497ec9fdde159a56ee42821e500b52d66374201 upgrade to latest `strict`

We could also release some fixes mentioned in the OP:
- [x] 5dd036739690e583b998b80cd873d8d4209f0766 fixing #4569
- [ ] @jespercockx 's 96af1a15733f0b52db9ce0fcb6379298409629c2 for #4526 (if it can be picked without conflicts)

**Comment by asr** [comment]
For fixing the current [fail](https://github.com/agda/agda/runs/1242720435) in GitHub workflows you need to cherry-pick e82cc844edb1c079acf5eebac7ab9beb9e83dd06.

Also for the changes for GHC 8.8.4 and 8.10.2 didn't include in 2.6.1.1 you need to cherry-pick cced69b7695078a5bc54a0eb0b6428ffb8033fe1, 75d06d4b1a8900fe2afe6e78ef34e1608b648b69, 4a93aa6ffbcc55df5e4f65ecb4dc1d6215501a79, eac32a3243c57de8aae09f90b448c576e537e849, 3f634a5d315cf205a8ee9cca4effa3560e69e7a2, 98a59d0e8ddef78341c504138019d604ebbf120d and ba5118947d358ce6edf8755d7882dc6d3c33e09e.

**Comment by andreasabel** [comment]
Oops, @asr, I did not see your comment.

I made a candidate release at https://hackage.haskell.org/package/Agda-2.6.1.2/candidate

I did not make sure the CI works on the release branch (it did not work where I picked it up from 2.6.1.1). I suppose the release branch is a detached development that will not be merged into master.
I tested stack compilation for 8.0.2 -- 8.10.2 on my machine.

**Comment by asr** [comment]
> I did not make sure the CI works on the release branch (it did not work where I picked it up from 2.6.1.1).

After releasing, the release branch should be ready for CI. I guess there were some steps missing in the last release. 

> I suppose the release branch is a detached development that will not be merged into master.

Right.

**Comment by andreasabel** [comment]
> After releasing, the release branch should be ready for CI. I guess there were some steps missing in the last release.

Indeed, CI was not set up for GHC 8.10 (which was the point of releasing 2.6.1.1).  I made some attempts to copy the more recent CI infrastructure to the release branch, but it does not work out-of-the-box, and I do not have the time (and knowledge) to fix this.  A **lot** of effort has gone into the CI since 2.6.1, and did not appear to me a simple cherry-picking (I might be wrong).  I rather tried to copy the CI stuff over from the master branch to the release branch and start cutting away unnecessary stuff, but to finish this will likely require many iterations of pushing-and-waiting-for-CI.

**Comment by asr** [comment]
@andreasabel Agda 2.6.1.2 is in Hackage. Please finish the release procedure (Wiki, announce, etc).

**Comment by asr** [comment]
I don't know if the `release-2.6.1.2` branch is ready for preparing the release of 2.6.1.3 (#5136). Anyway, I'll finish the release of 2.6.1.2.

**Comment by asr** [comment]
I updated the documentation in 'Read the docs' to 2.6.1.2.

**Comment by asr** [comment]
I deprecated in Hackage 2.6.1.1 and I updated the Wiki.

**Comment by asr** [comment]
Argh, I just noted that they are some supported GHC versions in 2.6.2.1 missing from https://agda.readthedocs.io/en/v2.6.1.2/getting-started/prerequisites.html.

**Comment by asr** [comment]
I made the announce.

**Comment by UlfNorell** [comment]
> I deprecated in Hackage 2.6.1.1 and I updated the Wiki.

2.6.1.2 doesn't work with ghc 8.10.3 does it? But 2.6.1.1 does, so isn't deprecating 2.6.1.1 a bad idea? (I'm not sure what the semantics of deprecation is)

**Comment by asr** [comment]
> 2.6.1.2 doesn't work with ghc 8.10.3 does it?

No, it doesn't.

I reverted the deprecation of 2.6.1.1 on Hackage. I'll deprecate 2.6.1.1 and 2.6.1.2 after the release of 2.6.1.3. Thank you for pointing out it.
