### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5442]
Umbrella issue for tracking progress of compiling under GHC 9.2.  Please add issues to the following list:
- [x] aeson (https://github.com/haskell/aeson/issues/885)
- [x] assoc (https://github.com/haskellari/assoc/issues/13)
- [x] base-compat (https://github.com/haskell-compat/base-compat/issues/74)
- [x] blaze-builder (https://github.com/lpsmith/blaze-builder/issues/23)
- [x] blaze-markup (jaspervdj/blaze-markup#56)
- [x] hashtables (https://github.com/gregorycollins/hashtables/issues/69, https://github.com/gregorycollins/hashtables/pull/70)
- [x] integer-logarithms (haskellari/integer-logarithms#29)
- [x] murmur-hash (nominolo/murmur-hash#13)
- [x] indexed-traversable (https://github.com/haskellari/indexed-traversable/issues/16)
- [x] primitive (https://github.com/haskell/primitive/pull/303)
- [x] random (https://github.com/haskell/random/pull/99, https://github.com/haskell/random/issues/110)
- [x] regex-tdfa (https://github.com/haskell-hvr/regex-tdfa/issues/23)

**Comment by andreasabel** [comment]
Magic incantation so far to start building Agda-2.6.3:
```
cabal build -w ghc-9.2.0 \
  --allow-newer=Agda:base \
  --allow-newer=Agda:template-haskell \
  --allow-newer=parallel:base \
  --allow-newer=murmur-hash:bytestring \
  --allow-newer=blaze-markup:base \
  --allow-newer=aeson:ghc-prim \
  --allow-newer=scientific:{base,template-haskell} \
  --allow-newer=integer-logarithms:{base,ghc-bignum,ghc-prim} \
  --allow-newer=aeson:template-haskell \
  --allow-newer=assoc:base \
  --allow-newer=indexed-traversable:base \
  --allow-newer=these:base \
  --allow-newer=time-compat:base \
  --allow-newer=data-fix:base \
  --allow-newer=indexed-traversable-instances:base \
  --allow-newer=semialign:base \
  --allow-newer=attoparsec:ghc-prim \
  --allow-newer=Agda:Cabal
```

**Comment by andreasabel** [comment]
Fixed by content of #5648.  
Follow-up issue: #5459.

**Comment by asr** [comment]
@andreasabel, please add 9.2.1 to https://agda.readthedocs.io/en/latest/getting-started/installation.html.
