### ISSUE TITLE
Release Agda 2.6.2.2

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#5831]
Agda-2.6.2.1 is not buildable with latest `bytestring` (#5718), so we need to re-release to stay in stackage-nightly once it switches to GHC 9.2.
The release could fork off branch `release-2.6.2.1`, cherry-picking the commit fixing #5718 and commits fixing regressions.

Organization:
- [x] branch `maint-2.6.2` picking commits from `master`
- [x] branch `release-2.6.2.2` adding to `maint-2.6.2` 2.6.2.2-specific commits (CHANGELOG, version)
- [x] branch `release-2.6.2.2-candidate` adding to `release-2.6.2.2` destructive commits (remove testsuite...); 2.6.2.2 will be released from this branch.

Included in release candidate 2.6.2.2-rc1 (ticked if they got a mention in the CHANGELOG):
- [x] support for `mtl-2.3` @andreasabel:
  * [x] #5659 
  * [x] #5798 
- [x] constructor instances @UlfNorell #5583 (#5685)
- [x] no generalize in let @UlfNorell #5683 (#5684 #5688)
- [x] reflection: scope of metas @jespercockx #5700
- [x] elaborate-and-give @jespercockx #5695
- [x] universe overflow @andreasabel #5705 #5706 (#5707)
- [x] bytestring-0.11.2 @andreasabel #5718 (#5723) 
- [x] some optimizations (meta, interface) @nad (#5733)
- [x] unicode GHC @nad #5742
- [ ] unicode readFile @nad #5741
- [x] run erased macros @jespercockx (#5744)
- [ ] MonadFail ST @andreasabel #5766 
- [x] pref freeze metas @nad #5388
- [x] text-icu-0.8.0 @andreasabel #5773 (#5779 #5783)
- [x] MAlonzo warning GHC 9.2 @andreasabel #5758 (#5759)
- [x] executables @UlfNorell #5762 (#5786)
- [x] instance/erasure @jespercockx #5787 (#5788)
- [x] tactic/erasure @jespercockx #5789 (#5790)
- [ ] duplicate include paths @nad #2506
- [x] cached interfaces @nad #2767
- [x] primEraseEquality @andreasabel #5784 (#5811)
- [x] irrelevant-projections @andreasabel #5809 (#5815)
- [x] termination reduce @andreasabel #5819 (#5821)
- [x] CI updates @andreasabel
  * [x] #5822 
  * [x] #5826 
  * [x] #5829

Additional picks for `rc2` (ticked if they got a mention in the CHANGELOG):
- [x] domTactic @andreasabel #5712 (#5717)
- [x] catch pattern violation in `checkType` @jespercockx #5805 (#5832)
- [x] switch stack-9.0.2 build to lts-19.0 @asr (#5852)
- [ ] pass AGDA_BIN to cubical-test @andreasabel (#5855)
- [x] switch stack-9.2.2 build to nightly @andreasabel (#5854)
- [x] inconsistency in cubical @andreasabel #5838 (#5846)

Still open unintended regressions in 2.6.2:
- [ ] fibrancy of blocked types @Saizan? #5681
- [ ] missing normalization in level solver @L-TChen  #5727 
- [ ] ellipsis parsing @gallais #5728

**Comment by asr** [comment]
@andreasabel, you can cherry-pick 1d9cd2227c1f4a36139a7df11282c2bccd0a5a76 in 2.6.2.2.

**Comment by andreasabel** [comment]
> @andreasabel, you can cherry-pick [1d9cd22](https://github.com/agda/agda/commit/1d9cd2227c1f4a36139a7df11282c2bccd0a5a76) in 2.6.2.2.

This would probably be painful and conflict with my added patches (_changelog hell_), but I'll release the content of this commit.

**Comment by andreasabel** [comment]
Agda 2.6.2.2 released from https://github.com/agda/agda/pull/5841 (tag v2.6.2.2).
