### ISSUE TITLE
Release 2.6.4

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6673]
The deadline for milestone 2.6.4 is approaching, so we should seriously think about the 2.6.4 release.
Release candidates should get version `2.6.3.2023mmdd` (optimistically assuming a release in 2023).

This issue is intended as a progress tracker and the issue description will be updated.

First steps:
- [ ] decide on open PRs (bump or finish)
- [ ] decide on open issues (bump or fix)

Issue priorities:
- [ ] regressions in new features (regression on master)
- [ ] issues with PR in place
- [ ] regressions in recent releases (e.g. 2.6.3)

Issues outside of these categories will by default be bumped to 2.6.5.

**Comment by andreasabel** [comment]
I did another round of bumping from 2.6.4 to 2.6.5.

**Comment by nad** [comment]
I think that one part of the release procedure should be a simple check that should rule out at least some performance regressions:

* Compile the previous release and the release candidate using the same recent version of GHC.
* Type-check the standard library a certain number of times using both versions of Agda (on the same, unloaded machine).
* The check fails if the previous version is clearly faster than the release candidate.

If the check fails then we have the option to release anyway, if there is a good reason for the slowdown.

**Comment by andreasabel** [comment]
Sounds reasonable, but we also need a volunteer doing this.

> * Type-check the standard library

"The standard library" might sometimes not exist, because we might make non-backwards compatible changes in Agda.  Probably this time we should be fine, we can use 1.7.2.

**Comment by MatthewDaggitt** [comment]
> "The standard library" might sometimes not exist, because we might make non-backwards compatible changes in Agda. Probably this time we should be fine, we can use 1.7.2.

In which case shouldn't the `experimental` branch be used?

**Comment by andreasabel** [comment]
> > "The standard library" might sometimes not exist, because we might make non-backwards compatible changes in Agda. Probably this time we should be fine, we can use 1.7.2.
> 
> In which case shouldn't the `experimental` branch be used?

Is this one guaranteed to work with the last release _and_ the current master of Agda?

**Comment by MatthewDaggitt** [comment]
No, it's only designed to work with the current master of Agda. You'd have to compare the last release of the Agda standard library + last release of Agda with `experimental` + current master of Agda. I don't think we can do any better than that.

**Comment by andreasabel** [comment]
Thanks for the clarification, @MatthewDaggitt !

**Comment by nad** [comment]
> "The standard library" might sometimes not exist, because we might make non-backwards compatible changes in Agda.

Sure, we should compare two versions of the standard library that are sufficiently close to each other, so that the test becomes meaningful. That might involve cherry-picking a small number of commits.

**Comment by andreasabel** [comment]
Check and/or improve titles of issues appearing that will be added to the CHANGELOG of 2.6.4:
- [x] [#1181](https://github.com/agda/agda/issues/1181): Display of let-bound variables in goals and error messages
- [x] [#3437](https://github.com/agda/agda/issues/3437): Add Propω
- [ ] [#3605](https://github.com/agda/agda/issues/3605): Improve constraint reporting for cubical
- [x] [#3690](https://github.com/agda/agda/issues/3690): Value of expression with interval variables instantiated
- [ ] [#5900](https://github.com/agda/agda/issues/5900): De Bruijn fail in Cubical (Was: Garbled boundary contexts & naming eta expansion.)
- [ ] [#6124](https://github.com/agda/agda/issues/6124): Cannot reduce type because variable is erased
- [x] [#6229](https://github.com/agda/agda/issues/6229): Print warning name along with warning text
- [ ] [#6271](https://github.com/agda/agda/issues/6271): Should generated code corresponding to erased constructors be erased?
- [ ] [#6272](https://github.com/agda/agda/issues/6272): Put Level type in a different sort?
- [x] [#6309](https://github.com/agda/agda/issues/6309): Drop support for GHC 8.0, 8.2, and 8.4
- [x] [#6325](https://github.com/agda/agda/issues/6325): Hidden argument puns
- [x] [#6333](https://github.com/agda/agda/issues/6333): Misleading file path in "Unrecognised option" error
- [x] [#6336](https://github.com/agda/agda/issues/6336): Paradoxical self-reference in endpoints for path constructors
- [ ] [#6364](https://github.com/agda/agda/issues/6364): Definitionally equal types do not admit the same term.
- [ ] [#6371](https://github.com/agda/agda/issues/6371): unsolved Metas should specify where they arise
- [ ] [#6374](https://github.com/agda/agda/issues/6374): Refine does not work for overloaded record constructors
- [ ] [#6380](https://github.com/agda/agda/issues/6380): Confusing warning about turning instances into instances
- [ ] [#6395](https://github.com/agda/agda/issues/6395): `dataXXX` identifiers mis-parsed by {-# COMPILE GHC #-}
- [ ] [#6407](https://github.com/agda/agda/issues/6407): Agsy produces clauses with out of scope variables
- [ ] [#6413](https://github.com/agda/agda/issues/6413): Miscompilation of nested patterns in erased fields
- [ ] [#6415](https://github.com/agda/agda/issues/6415): Apparent infinite loop in cubical with --lossy-unification
- [ ] [#6418](https://github.com/agda/agda/issues/6418): Bug in rewriting with cubical primitives
- [ ] [#6434](https://github.com/agda/agda/issues/6434): Option to increase performance: do not filter out absurd clauses automatically
- [x] [#6448](https://github.com/agda/agda/issues/6448): Is it OK to define dependencies for elisp files included in the agda2-mode package?
- [ ] [#6506](https://github.com/agda/agda/issues/6506): With abstraction failing to Type Check
- [ ] [#6521](https://github.com/agda/agda/issues/6521): Support GHC 9.6 with cabal
- [ ] [#6523](https://github.com/agda/agda/issues/6523): Soundness bug: Tick constraints not properly propogated in Guarded Cubical
- [ ] [#6524](https://github.com/agda/agda/issues/6524): Ignore Unicode byte order mark
- [ ] [#6525](https://github.com/agda/agda/issues/6525): Recent Emacs's escape character handling improvement leads to an error when loading agda-mode
- [ ] [#6530](https://github.com/agda/agda/issues/6530): Miscompilation of case split RHS lambdas
- [ ] [#6541](https://github.com/agda/agda/issues/6541): Internal error in Agda.TypeChecking.Reduce.Fast
- [ ] [#6551](https://github.com/agda/agda/issues/6551): The keywords `hiding`,`public`, `renaming`, and `using` are always reserved
- [ ] [#6573](https://github.com/agda/agda/issues/6573): Check on presence of `--erasure` in `--erase-record-parameters` comes too early
- [ ] [#6574](https://github.com/agda/agda/issues/6574): Sort out `--exact-split` vs. `-WCoverageNoExactSplit`
- [ ] [#6581](https://github.com/agda/agda/issues/6581): No canonicity for record types without η-equality?
- [ ] [#6605](https://github.com/agda/agda/issues/6605): Comments in "libraries" file
- [ ] [#6621](https://github.com/agda/agda/issues/6621): Enable K also for SSet\omega (like for SSet)
- [ ] [#6622](https://github.com/agda/agda/issues/6622): Nicifier has rubbish error for unsupported mutual recursion
- [ ] [#6624](https://github.com/agda/agda/issues/6624): Suffix not working for SSet
- [ ] [#6627](https://github.com/agda/agda/issues/6627): CheckArguments call exposes dummy checkArguments return type
- [ ] [#6632](https://github.com/agda/agda/issues/6632): hcompU eta rule in conversion checker loses solution
- [ ] [#6633](https://github.com/agda/agda/issues/6633): Bad interaction of Type:Type and SSet ?
- [ ] [#6648](https://github.com/agda/agda/issues/6648): `--level-universe` not respected when solving funSort `_->_ : ? -> Set -> SetOmega`
- [ ] [#6651](https://github.com/agda/agda/issues/6651): Agda fails on `univSort ? = SetOmega` even when `SizeUniv` is a solution
- [ ] [#6662](https://github.com/agda/agda/issues/6662): Error message for unsafe conjunctions has wrong pluralization
- [ ] [#6677](https://github.com/agda/agda/issues/6677): Helper function type includes generalized parameters
- [ ] [#6687](https://github.com/agda/agda/issues/6687): Termination checker bug with CATCHALL
- [ ] [#6706](https://github.com/agda/agda/issues/6706): Shape-irrelevant variables marked as irrelevant in human-readable context
- [ ] [#6711](https://github.com/agda/agda/issues/6711): IMPOSSIBLE internal error on primStringUncons when no builtin Sigma provided
- [ ] [#6714](https://github.com/agda/agda/issues/6714): Compiling Agda HEAD with Emacs 29+ reports docstring error
- [ ] [#6715](https://github.com/agda/agda/issues/6715): Type checking loops on certain pattern match in cubical
- [ ] [#6720](https://github.com/agda/agda/issues/6720): IMPOSSIBLE in Sort.hs during checking with cubical
- [ ] [#6725](https://github.com/agda/agda/issues/6725): IMPOSSIBLE in Reduce.hs

**Comment by andreasabel** [comment]
Here is a list with titles updated by github:
- [x] #1181
- [x] #3437
- [x] #3605
- [x] #3690
- [x] #5900
- [x] #6124
- [x] #6140
- [x] #6229
- [x] #6271
- [x] #6272
- [x] #6309
- [x] #6325
- [x] #6333
- [x] #6336
- [x] #6364
- [x] #6371
- [x] #6374
- [x] #6380
- [x] #6395
- [x] #6407
- [x] #6413
- [x] #6415
- [x] #6418
- [x] #6434
- [x] #6448
- [x] #6506
- [x] #6521
- [x] #6523
- [x] #6524
- [x] #6525
- [x] #6528
- [x] #6530
- [x] #6541
- [x] #6551
- [x] #6573
- [ ] ~~#6574~~
- [x] #6581
- [x] #6605
- [x] #6621
- [x] #6622
- [x] #6624
- [x] #6627
- [x] #6632
- [x] #6633
- [x] #6648
- [x] #6651
- [x] #6654
- [x] #6660
- [x] #6662
- [x] #6677
- [x] #6687
- [x] #6702
- [x] #6706
- [x] #6711
- [x] #6714
- [x] #6715
- [x] #6720
- [x] #6725
